version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: scs-fc-26-db
    environment:
      POSTGRES_DB: scs_fc_26
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
      - ./sample_data.sql:/docker-entrypoint-initdb.d/03-sample_data.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scs_fc_26"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: scs-fc-26-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@scsfc26.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
